server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
  redis:
    database: 1
    host: 47.98.114.150
    port: 7658
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: -1  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接